### ISSUE TITLE
Add Serbo-Croatian block list

### ISSUE THREAD

**Issue by fiftydinar** [secureblue/hardened-chromium-subresource-filter#12]
I'm not sure if it's compatible with subresource-filter, please take a look:

https://github.com/DandelionSprout/adfilt/blob/master/SerboCroatianList.txt

Covers Serbian, Croatian, Bosnian & Montenegrin websites.

**Comment by RoyalOughtness** [comment]
@fiftydinar seems fine to me, feel free to add it
